// ...no 'use client' here, keep as server component
import type { Metadata } from 'next';
import Navbar from './Components/Navbar/Navbar';
import { Nunito } from 'next/font/google';
import './globals.css';
import MobileNavBar from './Components/Navbar/Mobile/MobileNavBar';
import BaseUIProvider from './Components/BaseUIProvider';
import * as React from 'react';

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`}>
        <Navbar />
        <BaseUIProvider>{children}</BaseUIProvider>
        <MobileNavBar />
      </body>
    </html>
  );
}
