import type { Metadata } from "next";
import DatadogInit from "./Components/datadog-init";
import Navbar from "./Components/Navbar/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MobileNavBar from "./Components/Navbar/Mobile/MobileNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <DatadogInit />
        <Navbar/>
        {children}
        <MobileNavBar/>
      </body>
    </html>
  );
}
